config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trademarks
  
  resources :products

  root 'trademarks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :trademark

  validates :trademark_id, numericality: { only_integer: true, less_than: 9223372036854775807 }

  validates :name, presence: true, length: { minimum:3, maximum:50, too_short: "için en az %{count} karakter girilmelidir.", too_long: "için en fazla %{count} karakter girilebilir." }
  validates :sector, presence: true
  validates :price, presence: true, numericality: { only_integer: true, less_than: 2147483647 }
  validates :y_o_production, presence: true, length: {is: 4}, numericality: { only_integer: true, greater_than: 1949, less_than_or_equal_to: Time.now.year }
end

app/models/trademark.rb
class Trademark < ApplicationRecord
    has_one_attached :image
    has_many :products, dependent: :destroy

    validates :name, length: { minimum:3, maximum:50, too_short: "için en az %{count} karakter girilmelidir.", too_long: "için en fazla %{count} karakter girilebilir." }
    validates :description, length: { minimum:50, maximum:5000, too_short: "için en az %{count} karakter girilmelidir.", too_long: "için en fazla %{count} karakter girilebilir." } 
    validates :origin, presence: { message: "seçilmelidir." }
    web_regex = /(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?/ix
    validates :web, format: { with: web_regex, message: "örnek: http://www.ornek.com.. veya https://www.ornek.com..." }
    validate :correct_image_type

    private

        def correct_image_type
            if image.attached? && !image.content_type.in?(%w(image/jpeg image/png image/jpg))
                errors.add(:image, " görseli .jpg/ .jpeg/ .png uzantılı olmalıdır.")
            elsif image.attached? == false
                errors.add(:image, " seçilmelidir.")
            end
        end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :find_product, only: [:edit, :update, :destroy]
    before_action :select_of_trademarks, only: [:index, :new, :edit, :update]

    def index
        @products = Product.all.order("name ASC")
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new(product_params)
        @product.trademark_id = params[:product][:trademark_id]
        if @product.save
            flash[:notice] = "ürününüz başarıyla eklenmiştir"
            redirect_to products_path
        else
            render 'new'
        end
    end

    def edit
    end
    
    def update
        @product.trademark_id = params[:trademark_id]

        if @product.update(product_params)
            redirect_to products_path
        else
            render 'edit'
        end
    end
    
    def destroy
        @product.destroy
        redirect_to products_path
    end

    private

    def product_params
        params.require(:product).permit(:name, :sector, :price, :y_o_production, :trademark_id)
    end

    def find_product
        @product = Product.find(params[:id])
    end

    def select_of_trademarks
        @trademarks = Trademark.all.map{ |t| [t.name, t.id] }
    end

end

app/controllers/trademarks_controller.rb
class TrademarksController < ApplicationController
    before_action :find_trademark, only: [:edit, :update, :show, :destroy]

    def index
        @trademarks = Trademark.all.order("name ASC")
    end

    def new
        @trademark = Trademark.new
    end

    def create
        @trademark = Trademark.new(trademark_params)
        if @trademark.save
            redirect_to @trademark
        else
            render 'new'
        end
    end

    def show
        @products = Product.where(:trademark_id => params[:id]).order("created_at DESC")
    end

    def edit
    end

    def update
        if @trademark.update(trademark_params)
            redirect_to @trademark, notice: "Güncelleme işlemi yapıldı."
        else
            render 'edit'
        end
    end

    def destroy
        @trademark.destroy
        redirect_to trademarks_path
    end

    private

        def trademark_params
            params.require(:trademark).permit(:name, :description, :origin, :web, :image)
        end

        def find_trademark
            @trademark = Trademark.find(params[:id])
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/trademarks_helper.rb
module TrademarksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proje</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

  </head>
  

  <body>
  <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
		<div class="container">
			<div class="navbar-header col-md-1">
				<%= link_to "Proje", root_path, class: "navbar-brand"  %>
			</div>
      <ul class="nav navbar-nav col-md-10">
        <li><%= link_to "Marka", trademarks_path, class: "nav-link" %></li>
        <li><%= link_to "Ürün", products_path, class: "nav-link" %></li>
      </ul>
			<ul class="nav navbar-nav col-md-2">
				<% if user_signed_in? %>
					<li><%= link_to "Çıkış", destroy_user_session_path, method: :delete, class: "btn btn-outline-secondary"%></li>
				<% else %>
					<li><%= link_to "Kayıt Ol", new_user_registration_path, class: "btn btn-outline-info" %></li>
					<li><%= link_to "Giriş", new_user_session_path, class: "btn btn-outline-success" %></li>
				<% end %>
			</ul>
    </div>
  </nav>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  <footer class="footer bg-dark">
    <div class="container">
      <div class="d-flex justify-content-center">
          <%= link_to "#{image_tag("gitlab.png", style: 'height:auto;width:100px;')}".html_safe, "https://gitlab.com/ceburakyilmaz/proje" %>
      <div>
    </div>
  </footer>
  </body>
</html>

app/views/products/_form.html.haml
.container 
    .row
        .form-inputs
            =simple_form_for @product do |f|
                %p 
                //=select_tag(:trademark_id, options_for_select(@trademarks), :prompt => "Marka Seçiniz..", class: "form-select", label: "Marka")
                =f.input :trademark_id, collection: @trademarks, label: "Marka"
                %p 
                =f.input :name, label: "Ad", required: true
                %p 
                =f.input :sector, collection: [ "Bilişim Teknolojileri", "Elektrik ve Elektronik", "Gıda", "Otomotiv", "Finans"], :prompt => "Sektör Seçiniz..", label: "Sektör", required: true
                %p 
                =f.input :price, label: "Ücret", required: true
                %p 
                =f.input :y_o_production, collection: 1950..2021, label: "Üretim Yılı", required: true

                %p 
                =f.button :submit, class:"btn btn-success" 

app/views/products/edit.html.haml
.container 
    .row
        %h2 Ürün Düzenleme
        .form-inputs
            = simple_form_for @product do |f|
                =f.label :Marka 
                %p
                    =f.select :trademark_id, @trademarks, label: "Marka", class: "form-select-lg"
                %p 
                =f.input :name, label: "Ad"
                %p 
                =f.input :sector, collection: [ "Bilişim Teknolojileri", "Elektrik ve Elektronik", "Gıda", "Otomotiv", "Finans"], :prompt => "Sektör Seçiniz", label: "Sektör"
                %p 
                =f.input :price, label: "Ücret"
                %p 
                =f.input :y_o_production, collection: 1950..2021, label: "Üretim Yılı"

                %p 
                =f.button :submit, class: "btn btn-success"

app/views/products/index.html.haml
.container
    .row
        .col-md-10
            %h1 Ürünler
        .col-md-2
            -if user_signed_in?
                =link_to "Ürün Ekle", new_product_path, class:"btn btn-outline-success btn-lg"
        .col-md-12
        %hr/
        %table
            %tbody
                %tr
                    %td
                        %h5 İsim
                    %td 
                        %h5 Sektör
                    %td 
                        %h5 Ücret
                    %td 
                        %h5 Üretim Yılı
                    %td 
                        %h5 Marka Adı
                    %td{:colspan => 2 }
                        %h5 İşlemler
                - @products.each do |pro|
                    %tr
                        %td=pro.name
                        %td=pro.sector
                        %td=pro.price
                        %td=pro.y_o_production
                        - @trademarks.each do |t|
                            -if t[1] == pro.trademark_id
                                %td= t[0] 
                        -if user_signed_in?
                            %td
                                = link_to "Düzenle", edit_product_path(pro.id), class: "btn btn-primary"
                                = link_to "Sil", product_path(pro.id), method: :delete, data: { confirm: "Silme işlemini onaylıyor musunuz?" }, class: "btn btn-danger"

app/views/products/new.html.haml
.container 
    .row
        %h2 Ürün Ekleme

        = render 'form'

app/views/trademarks/_form.html.haml
.container 
    .row
        .form-inputs
            =simple_form_for @trademark do |f|                
                %p 
                =f.input :name, label: "Ad", class: "form-input", required: true
                .custom-file
                =f.input :image, label: "Logo", required: true
                %p 
                =f.input :description, size:"50x10", label: "Açıklama", required: true
                %p 
                =f.input :origin, collection: [ "Türkiye", "ABD", "Çin", "Japonya", "İngiltere", "Almanya", "Fransa", "Hollanda"], :prompt => "Seçiniz", label: "Menşei", required: true
                %p 
                =f.input :web, :placeholder => "URL Adresi", required: true
                %p 
                =f.button :submit, class: "btn btn-success"

app/views/trademarks/edit.html.haml
.container 
    .row
        %h1 Marka Düzenle

        = render 'form'
        %br/

app/views/trademarks/index.html.haml
.container 
    .row
        .col-md-10
            %h1 Markalar
        .col-md-2 
            -if user_signed_in?
                = link_to "Marka Ekle", new_trademark_path, class:"btn btn-outline-primary btn-lg"
        %hr/
        %br/
        .div.d-flex.col-12
            - @trademarks.each do |t|
                .ana_div.col-2
                    .align-self-center
                        =image_tag(t.image, class: "image")
                    %h2=link_to t.name, t
                    %h6=link_to "Website", t.web

app/views/trademarks/new.html.haml
.container 
    .row
        %h1 Marka Ekle

        = render 'form'

app/views/trademarks/show.html.haml
.container 
    .row
        .col-md-10
            %h1 Marka Bilgileri
        .col-md-2 
            .links-btn-group
                %table
                    %tr 
                        -if user_signed_in?
                            %td=link_to "Düzenle", edit_trademark_path, class: "btn btn-primary btn-lg"
                            %td=link_to "Sil", trademark_path(@trademark), method: :delete, data: { confirm: "Marka ve markaya ait ürünler silinecektir! İşlemi onaylıyor musunuz?" }, class: "btn btn-danger btn-lg" 
        %hr/
        .col-md-2 
            %h2 Logo :
            = image_tag(@trademark.image, style: ' height:auto; width:200px; border: 2px dashed #000;')
        .col-md-10
            %h2 Ad :
            = @trademark.name
            %h4 Açıklama :
            = @trademark.description 
            %h5 Menşei :
            = @trademark.origin
            %h6 Web Site :
            = "#{link_to @trademark.web, @trademark.web}".html_safe
            %br/
            %br/
        %hr/
        .col-md-12
            %br/
            .container
                .row                   
                    .col-md-10
                        %h1 Markanın ürünleri
                    .col-md-2
                        -if user_signed_in?
                            =link_to "Ürün Ekle", new_product_path, class:"btn btn-outline-success btn-lg"
                    .col-md-12
                    %hr/
                    %table
                        %tbody
                            %tr
                                %td
                                    %h5 İsim
                                %td 
                                    %h5 Sektör
                                %td 
                                    %h5 Ücret
                                %td 
                                    %h5 Üretim Yılı
                                %td{:colspan => 2 }
                                    %h5 İşlemler
                            - @products.each do |pro|
                                %tr
                                    %td=pro.name
                                    %td=pro.sector
                                    %td=pro.price
                                    %td=pro.y_o_production
                                    -if user_signed_in?
                                        %td
                                            = link_to "Düzenle", edit_product_path(pro.id), class: "btn btn-primary"
                                            = link_to "Sil", product_path(pro.id), method: :delete, data: { confirm: "Silme işlemini onaylıyor musunuz?" }, class: "btn btn-danger"